import type { Exercise, Workout, Section } from './types';

let n=0;
const e=(name:string,section:Section,sets:number,reps:string,tempo:string,rest:number,cue:string,load=''):Exercise=>({id:`e${++n}`,name,section,sets,reps,tempo,rest,cue,load});
const warm=(type:string)=>e(type,'Rozgrzewka',1,'8–10 min','spokojnie',0,'Oddychaj swobodnie. Tempo pozwala mówić pełnymi zdaniami.');
const cardio=(type:string,min:string)=>e(type,'Cardio',1,min,'strefa 2',0,'Równe tempo, bez zadyszki; możesz prowadzić rozmowę.');
const cool=(a:string,b:string)=>e(`${a} + ${b}`,'Wyciszenie',1,'5 min','30 s / pozycję',0,'Bez sprężynowania i bez bólu. Oddychaj spokojnie.');
const s=(name:string,sets:number,reps:string,cue:string,load='lekko')=>e(name,'Siła i stabilizacja',sets,reps,'3–1–2',75,cue,load);

export const workouts:Workout[]=[
{day:1,title:'Spokojny start',focus:'Całe ciało • nauka tempa',duration:'40–45 min',cardio:'Rower 10 min',exercises:[warm('Rower + mobilizacja barków'),s('Sit To Stand',2,'8','Stopy pod kolanami. Wstań z wydechem, nie pochylaj się gwałtownie.','masa ciała'),s('Seated Row',2,'10','Klatka wysoko, łopatki lekko do tyłu; nie odchylaj tułowia.'),s('Leg Curl',2,'10','Biodra dociśnięte, ruch bez szarpania.'),s('Wall Push Up',2,'8','Ciało w jednej linii, wydech przy odepchnięciu.','masa ciała'),s('Hip Abductor',2,'12','Miednica nieruchomo, nie rozpędzaj maszyny.'),s('Bird Dog',2,'6 / strona','Wydłuż kończyny, brzuch tylko delikatnie aktywny; bez zapadania lędźwi.','masa ciała'),cardio('Rower','10 min'),cool('Hip Flexor Stretch','Calf Stretch')]},
{day:2,title:'Plecy i biodra',focus:'Postawa • pośladki',duration:'40–45 min',cardio:'Bieżnia 12 min',exercises:[warm('Marsz + Cat Cow + krążenia bioder'),s('Lat Pulldown',2,'10','Ściągnij drążek do górnej klatki bez odchylania tułowia.'),s('Glute Machine',2,'10 / strona','Mały zakres, miednica stabilna; wydech w fazie pracy.'),s('Chest Press',2,'10','Lekki ciężar, łopatki oparte, nie wstrzymuj oddechu.'),s('Side Steps z miniband',2,'8 / strona','Krótkie kroki, kolana kieruj nad stopy.','lekka guma'),s('Face Pull',2,'12','Prowadź linkę do twarzy, barki daleko od uszu.'),s('Dead Bug — heel taps',2,'6 / strona','Dotykaj piętą podłogi; przerwij przy ciągnięciu brzucha.','masa ciała'),cardio('Bieżnia — szybki marsz','12 min'),cool('Thoracic Rotation','Hamstring Stretch')]},
{day:3,title:'Kolana bez presji',focus:'Nogi • kontrola ruchu',duration:'42–47 min',cardio:'Orbitrek 12 min',exercises:[warm('Orbitrek + mobilizacja skokowych'),s('Leg Press — płytki zakres',2,'10','Kolana nad stopami. Zatrzymaj zakres przed bólem; bez blokowania kolan.'),s('Box Squat',2,'8','Usiądź lekko na wysokim boxie i wstań z wydechem.','masa ciała'),s('Cable Row',2,'10','Stabilna pozycja, łokcie prowadź wzdłuż tułowia.'),s('Clamshell',2,'10 / strona','Biodra jedno nad drugim, nie roluj miednicy.','masa ciała'),s('Leg Extension — tylko bez bólu',2,'8','Bardzo lekko, płynnie; pomiń przy bólu kolana.'),s('Band Pull Apart',2,'12','Żebra spokojnie, rozciągnij gumę ruchem łopatek.','lekka guma'),cardio('Orbitrek','12 min'),cool('Calf Stretch','Hip Flexor Stretch')]},
{day:4,title:'Góra i oddech',focus:'Klatka • plecy • barki',duration:'38–43 min',cardio:'Rower 10 min',exercises:[warm('Rower + mobilizacja barków i odcinka piersiowego'),s('Dumbbell Press na ławce skośnej',2,'8','Bardzo lekko; wydech podczas wyciskania, bez parcia.','2 × lekki hantel'),s('Dumbbell Row z podparciem',2,'10 / strona','Podeprzyj jedną rękę, plecy neutralnie; nie skręcaj tułowia.','lekki hantel'),s('Shoulder Press — maszyna',2,'8','Minimalny ciężar, nie unoś barków i nie przeprostuj pleców.'),s('Hip Adductor',2,'12','Łagodnie zbliż uda; miednica oparta.'),s('Glute Bridge',2,'10','Wydech przy uniesieniu, zatrzymaj przed napięciem blizny.','masa ciała'),s('Standing Pallof Press',2,'8 / strona','Lekki opór; miednica i żebra nieruchomo, oddychaj.','lekka linka'),cardio('Rower','10 min'),cool('Chest Stretch','Thoracic Rotation')]},
{day:5,title:'Chód i równowaga',focus:'Stabilność • pośladki',duration:'42–47 min',cardio:'Bieżnia 15 min',exercises:[warm('Marsz + aktywacja pośladków'),s('Step Up — niski stopień',2,'6 / strona','Cała stopa na stopniu, odpychaj się nogą z góry; poręcz dla wsparcia.','masa ciała'),s('Seated Row — chwyt neutralny',2,'10','Łokcie blisko ciała, zatrzymaj na sekundę.'),s('Hip Abductor',2,'12','Kontroluj powrót, bez kołysania.'),s('Incline Push Up — wysoka podpórka',2,'8','Wysoka ławka, wydech przy odepchnięciu; bez napinania brzucha.','masa ciała'),s('Farmer Walk',3,'30 s','Lekkie hantle, wysoka sylwetka, swobodny oddech.','2 × lekki hantel'),s('Bird Dog — same nogi',2,'6 / strona','Wysuwaj stopę po podłodze, miednica pozostaje nieruchoma.','masa ciała'),cardio('Bieżnia — marsz','15 min'),cool('Hamstring Stretch','Calf Stretch')]},
{day:6,title:'Tył ciała lekko',focus:'Pośladki • tył uda',duration:'43–48 min',cardio:'Orbitrek 12 min',exercises:[warm('Orbitrek + Hip Hinge przy ścianie'),s('Romanian Deadlift z hantlami',2,'8','Minimalny ciężar, biodra w tył, hantle blisko ud; bez parcia.','2 × bardzo lekki hantel'),s('Leg Curl',2,'12','Powoli zegnij kolana, biodra pozostają oparte.'),s('Lat Pulldown — chwyt neutralny',2,'10','Zacznij łopatkami, bez bujania.'),s('Glute Bridge — pauza',2,'8','Pauza 2 s u góry; ruch ma być komfortowy dla brzucha.','masa ciała'),s('Chest Press',2,'10','Lekki opór, wydech przy wypchnięciu.'),s('Clamshell z miniband',2,'10 / strona','Mały zakres bez skrętu miednicy.','lekka guma'),cardio('Orbitrek','12 min'),cool('Hip Flexor Stretch','Hamstring Stretch')]},
{day:7,title:'Regeneracja aktywna',focus:'Mobilność • lekka stabilizacja',duration:'35–40 min',cardio:'Rower 15 min',exercises:[warm('Rower spokojny + oddech żebrowy'),s('Cat Cow',2,'6','Mały, komfortowy zakres; zsynchronizuj ruch z oddechem.','masa ciała'),s("World’s Greatest Stretch — wersja podparta",2,'4 / strona','Ręce na wysokim podparciu, bez mocnego skrętu brzucha.','masa ciała'),s('Thoracic Rotation w siadzie',2,'6 / strona','Obracaj górę pleców, biodra nieruchomo.'),s('Sit To Stand',2,'8','Płynnie wstań i usiądź, użyj wyższej ławki.','masa ciała'),s('Band Pull Apart',2,'10','Lekka guma, barki nisko.','lekka guma'),cardio('Rower','15 min'),cool('Hip Flexor Stretch','Calf Stretch')]},
{day:8,title:'Nowy krok',focus:'Całe ciało • delikatna progresja',duration:'44–49 min',cardio:'Bieżnia 12 min',exercises:[warm('Bieżnia + mobilizacja bioder i barków'),s('Goblet Squat do boxa',2,'8','Bardzo lekki hantel przy klatce, wysoki box, wydech w górę.','bardzo lekki hantel'),s('Cable Row',3,'10','Klatka spokojnie wysoko, bez przeprostu lędźwi.'),s('Glute Machine',2,'12 / strona','Mały kontrolowany ruch, nie skręcaj miednicy.'),s('Wall Push Up — wolno',2,'10','Trzy sekundy do ściany, wydech przy odepchnięciu.','masa ciała'),s('Leg Curl',2,'10','Zatrzymaj 1 s po zgięciu.'),s('Standing Pallof Hold',2,'15 s / strona','Bardzo lekki opór i ciągły oddech; bez drżenia.','lekka linka'),cardio('Bieżnia — szybki marsz','12 min'),cool('Thoracic Rotation','Hamstring Stretch')]},
{day:9,title:'Postawa premium',focus:'Plecy • barki • biodra',duration:'40–45 min',cardio:'Orbitrek 12 min',exercises:[warm('Orbitrek + krążenia barków'),s('Lat Pulldown',3,'8','Lekko, łokcie w dół; szyja rozluźniona.'),s('Face Pull',2,'12','Dłonie do skroni, łopatki pracują bez unoszenia barków.'),s('Hip Adductor',2,'12','Kontroluj oba kierunki ruchu.'),s('Dumbbell Press — podłoga lub ławka',2,'8','Neutralny chwyt, bardzo lekko, wydech w górę.','2 × lekki hantel'),s('Side Steps z miniband',2,'10 / strona','Napięta guma, małe kroki, stopy równolegle.','lekka guma'),s('Dead Bug — ruch jednej ręki',2,'6 / strona','Ruszaj tylko ręką; brzuch ma pozostać komfortowy.','masa ciała'),cardio('Orbitrek','12 min'),cool('Chest Stretch','Hip Flexor Stretch')]},
{day:10,title:'Mocne nogi, spokojne kolana',focus:'Nogi • pośladki',duration:'45–50 min',cardio:'Rower 15 min',exercises:[warm('Rower + mobilizacja kolan i bioder'),s('Leg Press',3,'10','Lekki ciężar, komfortowy zakres, kolana zgodnie z palcami.'),s('Step Up — niski stopień',2,'8 / strona','Powoli zejdź; użyj poręczy, jeśli poprawia kontrolę.','masa ciała'),s('Seated Row',2,'12','Bez odchylania, pauza przy tułowiu.'),s('Hip Abductor',2,'15','Lekki opór, kontrolowany powrót.'),s('Leg Extension — tylko bez bólu',2,'10','Mały ciężar; ból oznacza pominięcie ćwiczenia.'),s('Farmer Walk',3,'35 s','Krótkie spokojne kroki, bez wstrzymywania oddechu.','2 × lekki hantel'),cardio('Rower','15 min'),cool('Quad Stretch stojąc','Calf Stretch')]},
{day:11,title:'Pchanie i przyciąganie',focus:'Góra ciała • stabilna sylwetka',duration:'40–45 min',cardio:'Bieżnia 10 min',exercises:[warm('Marsz + mobilizacja łopatek'),s('Chest Press',3,'8','Łopatki oparte; wydech przy ruchu od klatki.'),s('Cable Row — wąski chwyt',3,'8','Przyciągnij bez kołysania tułowiem.'),s('Shoulder Press — bardzo lekko',2,'8','Zakres tylko komfortowy, żebra nie uciekają w górę.'),s('Glute Bridge',2,'12','Napnij pośladki, nie wypychaj wysoko brzucha.','masa ciała'),s('Band Pull Apart',2,'12','Ręce na wysokości mostka, bez przeprostu.'),s('Bird Dog',2,'7 / strona','Wolno, z wydechem; skróć dźwignię, jeśli czujesz brzuch.','masa ciała'),cardio('Bieżnia — marsz','10 min'),cool('Chest Stretch','Thoracic Rotation')]},
{day:12,title:'Biodra i balans',focus:'Kontrola jednej nogi • mobilność',duration:'43–48 min',cardio:'Orbitrek 15 min',exercises:[warm('Orbitrek + mobilizacja bioder'),s('Box Squat — wysoki box',3,'8','Lekki dotyk boxa, równy nacisk obu stóp.','masa ciała'),s('Glute Machine',3,'10 / strona','Prowadź ruch pośladkiem, nie lędźwiami.'),s('Dumbbell Row z podparciem',2,'12 / strona','Stabilny tułów i spokojny wydech.','lekki hantel'),s('Clamshell',2,'12 / strona','Pięty razem, miednica nieruchoma.','lekka guma'),s('Incline Push Up',2,'10','Wysokie podparcie, łokcie około 45° od tułowia.','masa ciała'),s('Pallof Press — pół kroku od wyciągu',2,'8 / strona','Najlżejszy opór; bez skrętu i bez parcia.','lekka linka'),cardio('Orbitrek','15 min'),cool('Hip Flexor Stretch','Hamstring Stretch')]},
{day:13,title:'Pełne ciało w rytmie',focus:'Płynność • pewność ruchu',duration:'45–50 min',cardio:'Bieżnia 15 min',exercises:[warm('Bieżnia + Cat Cow + mobilizacja barków'),s('Goblet Squat do boxa',2,'10','Lekko i płynnie, zatrzymaj przed bólem kolan.','bardzo lekki hantel'),s('Lat Pulldown',2,'12','Bez odchylania, kontroluj powrót drążka.'),s('Romanian Deadlift z hantlami',2,'10','Mały zakres, neutralne plecy, wydech przy wyproście.','2 × bardzo lekki hantel'),s('Dumbbell Press na ławce skośnej',2,'10','Lekko, stały oddech, bez wypychania żeber.','2 × lekki hantel'),s('Hip Abductor',2,'12','Pauza w odwiedzeniu, wolny powrót.'),s('Farmer Walk',3,'40 s','Lekki chwyt, wyprostowana sylwetka, swobodny oddech.','2 × lekki hantel'),cardio('Bieżnia — szybki marsz','15 min'),cool('Calf Stretch','Thoracic Rotation')]},
{day:14,title:'Finał i samoocena',focus:'Całe ciało • jakość techniki',duration:'45–50 min',cardio:'Rower 15 min',exercises:[warm('Rower + ulubiona mobilizacja'),s('Leg Press — komfortowy zakres',2,'12','Wybierz ciężar RPE 5–6; bez blokowania kolan.'),s('Seated Row',2,'12','Pauza 1 s, szyja rozluźniona.'),s('Glute Bridge',2,'12','Równy nacisk stóp, wydech przy uniesieniu.','masa ciała'),s('Wall Push Up',2,'12','Płynnie, ciało w jednej linii.','masa ciała'),s('Side Steps z miniband',2,'10 / strona','Kolana miękkie, miednica poziomo.','lekka guma'),s('Bird Dog',2,'8 / strona','Najlepsza jakość ruchu; zatrzymaj przy dyskomforcie.','masa ciała'),cardio('Rower','15 min'),cool('Hip Flexor Stretch','Hamstring Stretch')]}
];

export const safety=['Ból, pieczenie lub ciągnięcie blizny → przerwij ćwiczenie','Nie wstrzymuj oddechu; wydech w fazie wysiłku','Zostań przy RPE 5–6/10 i zachowaj 3–4 powtórzenia w zapasie','Ból kolana powyżej 3/10 → skróć zakres albo pomiń ruch'];
